### PR TITLE
fix: make nav and footer modal configurable

### LINKED ISSUE #557: New SEM Pages - Header/Footer Get A Quote
The Get  A Quote button on the new SEM pages header and footer is incorrect. It currently launches the generic multistep form used across the site. These new SEM pages that use this template should be mapped to the form that applies to the page. On the inline form page it should be  https://main--shredit--stericycle.aem.page/forms/landing-page-modal. Part of the challenge is we use different forms on different pages. In our current set-up the header and footer are authorable elements within each page to allow this flexibility. 

This only applies to the marketing pages that have the new template (navy blue header with links, wider margins).

Example:
https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

Should match:
https://www.shredit.com/en-us/marketing/shred-it-document-destruction-inline#who-we-are

### PR DESCRIPTION
**Pull request by ravise5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #557 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
  - https://main--shredit--stericycle.aem.page/en-us
- After: 
  - https://issue557--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
  - https://issue557--shredit--stericycle.aem.page/en-us

### CODE REVIEW

File: blocks/footer/footer.js [hunk 1]
```diff
@@ -64,6 +65,28 @@ function createMenuAccordion(footer) {
...
+ * @param fragment
+ * @param footerPath
+ * @param locale
+ * Creates the modal trigger button in footer
+ */
+function createModalButton(fragment, footerPath, locale) {
+  const footerModalPath = getMetadata('footer-modal-path') || '/forms/modals/modal';
+  const btn = p(
+    { class: 'button-container quote-wrapper' },
+    a({ href: footerModalPath, class: 'quote-button button primary', 'aria-label': 'Request a Free Quote' }, 'Request a Free Quote'),
```
Comment (jindaliiita) [inline blocks/footer/footer.js:78]: Are we not handling the static text for placeholders in forms for other locales ?

**Comment by jindaliiita** [comment]
LGTM Thanks
@bstopp, can you also take a look to ensure that nothing related to the header is breaking ?

**Review by jindaliiita — APPROVED** [review]

**Review by bstopp — APPROVED** [review]
