### PR TITLE
fix: exclude hidden fields from validation during submission

### LINKED ISSUE #745: Form Submission Issue - Multistep Form Submission Issue
@MarquiseRosier @ravise5 just found a major issue with out multistep forms. If you select any service other than One Time it does not allow you to submit the form.

It looks like the issue is with the fourth step. 

If I select anything other than one time (e.g. hard drive) and try to submit nothing happens. It doesn't show any errors but it does not successfully submit.

Image

If I go back and switch the service to one time, and then go through the steps I see a validation error on the how quickly do you need this service question which now appears. 

Image

It seems like the form is seeing how quickly do you need this service as mandatory field regardless of service selection. This field should only appear and apply to One Time service. 

Can you ensure this is fixed? This should the top priority. 

The is happening on all modal forms - https://stage-us.shredit.com/en-us

And on inline multistep forms - https://stage-us.shredit.com/en-us/who-we-serve/auto

These needs to fixed for all forms on all pages.

### PR DESCRIPTION
**Pull request by ravise5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #745 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/
- After: 
  - https://issue745--shredit--stericycle.aem.page/

### CODE REVIEW

**Review by MarquiseRosier — APPROVED** [review]

File: blocks/form/lib/forms-common.js [hunk 1]
```diff
@@ -398,7 +398,10 @@ function enableValidation(form) {
 
 async function handleSubmit(e, form, captcha, submitHandler) {
   e.preventDefault();
+  const hiddenFields = form.querySelectorAll('[data-visible="false"]');
+  hiddenFields.forEach(((field) => { field.disabled = true; })); // disabled fields are skipped for validation
```
Comment (jalagari) [inline blocks/form/lib/forms-common.js:402]: please check if this data need to be sent to backend or not? If its disabled I doubt data will not be sent to server

**Review by jalagari — APPROVED** [review]

File: blocks/form/lib/forms-common.js (hunk 1 above)
Comment (ravise5) [reply blocks/form/lib/forms-common.js:402]: Data is getting submitted
